version: "3.8"

services:
  python:
    image: python:3.12
    container_name: python_container
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/bash